### ISSUE TITLE
【ChatGPT快速注册登录全攻略】

### ISSUE THREAD

**Issue by ClashPacfree** [reorx/awesome-chatgpt-api#32]
10秒钟搞定ChatGPT注册登录攻略：[ChatGPT注册登录攻略](https://github.com/xiaoming2028/FreePAC/wiki/ChatGPT%E6%B3%A8%E5%86%8C%E6%95%99%E7%A8%8B%EF%BC%88%E5%AE%8C%E6%95%B4%E6%8C%87%E5%8D%97%EF%BC%89)

ChatGPT副业赚钱技巧超详细：[ChatGPT副业赚钱方法分享](https://github.com/xiaoming2028/Chatgpt-Makes-Money)

**Comment by reorx** [comment]
that's nonsense
