### ISSUE TITLE
Add Ninja Extractor

### ISSUE THREAD

**Issue by restyler** [reorx/awesome-chatgpt-api#49]
Hi!
I think this repo might be improved by adding another awesome API tool (I am the author)
https://rapidapi.com/restyler/api/article-extractor-and-summarizer/
Not sure which category is the best.

This is an API which extracts article body from a URL and uses GPT to summarize the article content. Leverages powerful and flexible web scraping engine with rotating proxies under the hood. In depth review and API implementation details: https://pixeljets.com/blog/gpt-summary-is-broken/

Cheers!
Anthony.

**Comment by reorx** [comment]
Hi Anthony, this project is really an awesome API, but not a project that allows users to set their own API key (see #21), so I have to close this issue for now. I find it inspiring and plan to incorporate it into a future project that has broader collection standards. Thank you for your suggestion.
