### ISSUE TITLE
希望大家找一下GUI类型的工具并收录

### ISSUE THREAD

**Issue by mm615657** [reorx/awesome-chatgpt-api#6]
个人情况（需求）是希望有个相对比较纯粹的gui客户端，提供一些基础的功能即可。比如输入输出管理，将历史或上下文包装成对话，使用系统代理或者适配其他各种奇怪的网络环境。
我简单找了一下目前的两个gui工具一个很简陋一个似乎遇到了代码以外的问题…所以来这里希望大家能一起注意一下是否有类似的工具值得收录。

**Comment by reorx** [comment]
目前的 GUI 我也不满意，但短时间内可能不会有更好的，大家现在都急着做新玩意而没时间优化软件功能、增加应用场景深度，我们拭目以待吧

**Comment by Tamrac-web** [comment]
I'm finding for this too!

**Comment by eryajf** [comment]
目前看了一圈，的确没有太理想的，我这边提供一个思路，我通过一个web的项目自己部署在verecl，然后使用MenubarX挂着，再绑定个快捷键，用的时候快捷键调用出来，即用即走，感觉还算蛮方便的：

![image](https://user-images.githubusercontent.com/33259379/223637134-e4853ba0-d9bd-4662-9874-5f683cac301f.png)

**Comment by feitian124** [comment]
baye 有个 opencat，不过似乎不开源？

**Comment by reorx** [comment]
GUI 工具目前已有很多在 [Web Apps - ChatGPT-like Web UI](https://github.com/reorx/awesome-chatgpt-api#chatgpt-like-web-ui) 和 [Desktop & Mobile Apps - ChatGPT-like Web UI](https://github.com/reorx/awesome-chatgpt-api#chatgpt-like-web-ui) 两个分类下，因此本 issue 可以 close 了
