### ISSUE TITLE
Add Ultimate ChatGPT

### ISSUE THREAD

**Issue by imabutahersiddik** [reorx/awesome-chatgpt-api#68]
**Website URL**

```
https://chatgpt.kiask.xyz/
```

**Website Type**

- [x] ChatGPT site
- [ ] Other

**Website Description and Usage**

> Please provide a clear description to help others understand how to use it.

- [x] 😄 Free to use (open and ready to use with no restrictions)
- [ ] 🔑 Free to use, but requires login or password
- [ ] 🤑 Paid service
- [ ] 🎁 Paid service with a trial period

**Website Icon - Path (optional)**
> Square-shaped icon

```
For example: https://chatgpt.kiask.xyz/android-chrome-512x512.png
```

**Requires International Access (optional)**

- [x] No
- [ ] Yes

**Comment by reorx** [comment]
This site, from my perspective, is a clone or fork of https://github.com/Yidadaa/ChatGPT-Next-Web, which I have been added to the collection.
