### ISSUE TITLE
TeamSmart AI is dead

### ISSUE THREAD

**Issue by inspiredearth** [reorx/awesome-chatgpt-api#80]
Hi there.
Thanks for sharing this list.
I suggest removing TeamSmart. Looks like it's not worked for past year or so, and the people/company that bought out TeamSamrt in 2023 has been anything but transparent with their intentions, leaving paying subscribers in the lurch.

**Comment by reorx** [comment]
It appears so. It has been a year since their last update of the Chrome extension.
